name: Hello World Workflow

on:
  push:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Run Hello World
      run: echo "Hello World! This workflow was triggered on $(date)"