name: SonarQube Plugin Compatibility Test

on:
  push:
    branches: [main]

jobs:
  SonarQube-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sonarqube-version:
          [
            "8.9",
            "9.6",
            "9.7",
            "9.8",
            "10.0.0",
            "10.1.0",
            "10.2.0",
            "10.3.0",
            "10.4.0",
            "10.5.0",
            "10.6.0",
            "10.7.0",
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup SonarQube
        uses: ./.github/actions/setup-sonarqube
        with:
          sonarqube-version: ${{ matrix.sonarqube-version }}

      - name: Install and verify plugin
        uses: ./.github/actions/install-plugin
        with:
          sonarqube-version: ${{ matrix.sonarqube-version }}
          plugin-path: com.checkmarx.sonar.cxplugin-2024.3.3.jar

      # - name: Run Maven tests
      #   working-directory: Sonarqube
      #   run: |
      #     mvn clean test

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup-sonarqube
        with:
          sonarqube-version: ${{ matrix.sonarqube-version }}