name: SonarQube Plugin Compatibility Test

on:
  push:
    branches: [main]

jobs:
  SonarQube-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sonarqube-version: ["10.1.0", "10.7.0"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Start SonarQube ${{ matrix.sonarqube-version }}
        run: |
          podman run -d --name sonar-${{ matrix.sonarqube-version }} \
            -p 9000:9000 \
            docker.io/sonarqube:${{ matrix.sonarqube-version }}-community

          # Wait for initial startup
          echo "Waiting for SonarQube initial startup..."
          until curl -sSf http://localhost:9000/api/system/status | grep -q "UP"; do sleep 10; done

      - name: Status Before Plugin
        run: |
          echo "SonarQube status before plugin installation:"
          curl -sSf http://localhost:9000/api/system/status

      - name: Install Plugin
        run: |
          podman cp com.checkmarx.sonar.cxplugin-2024.3.3.jar sonar-${{ matrix.sonarqube-version }}:/opt/sonarqube/extensions/plugins/
          podman restart sonar-${{ matrix.sonarqube-version }}

      - name: Verify Plugin Installation
        run: |
          echo "Waiting for SonarQube to restart after plugin installation..."
          for i in {1..30}; do
            if curl -sSf http://localhost:9000/api/system/status | grep -q "UP"; then
              echo "SonarQube is up after plugin installation!"
              break
            fi
            echo "Waiting for SonarQube to start... ($i/30)"
            sleep 10
          done

          # Check final status
          echo "Final SonarQube status:"
          curl -sSf http://localhost:9000/api/system/status

          # Check logs for plugin loading errors
          echo "Checking SonarQube logs for plugin loading..."
          podman logs sonar-${{ matrix.sonarqube-version }} | grep -i "plugin"

          # Try to access the plugin's endpoints (if any)
          echo "Checking plugin endpoints..."
          curl -sSf http://localhost:9000/api/checkmarx/settings | grep -q "error" && echo "Plugin endpoint accessible" || echo "Plugin endpoint not accessible"

      - name: Shutdown
        run: |
          podman stop sonar-${{ matrix.sonarqube-version }}
          podman rm -v sonar-${{ matrix.sonarqube-version }}